// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWq_gHN7mTe77nkypt3KBzVLSM8lpCzV8',
    appId: '1:242189819890:web:213eafbaf7ba63e7ed556b',
    messagingSenderId: '242189819890',
    projectId: 'birthdays-reminder-313',
    authDomain: 'birthdays-reminder-313.firebaseapp.com',
    storageBucket: 'birthdays-reminder-313.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhkdEASSqKhD62tK_olZJfII9DUYrl0QU',
    appId: '1:242189819890:android:f0c57ef75580dd80ed556b',
    messagingSenderId: '242189819890',
    projectId: 'birthdays-reminder-313',
    storageBucket: 'birthdays-reminder-313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFfe28vsAWOaH04RT_gqldvmCskZQJKhM',
    appId: '1:242189819890:ios:fcc3d2d30d633532ed556b',
    messagingSenderId: '242189819890',
    projectId: 'birthdays-reminder-313',
    storageBucket: 'birthdays-reminder-313.appspot.com',
    iosBundleId: 'com.sebastianlech.birthdaysReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFfe28vsAWOaH04RT_gqldvmCskZQJKhM',
    appId: '1:242189819890:ios:ceb5c91cf68d0857ed556b',
    messagingSenderId: '242189819890',
    projectId: 'birthdays-reminder-313',
    storageBucket: 'birthdays-reminder-313.appspot.com',
    iosBundleId: 'com.sebastianlech.birthdaysReminderApp.RunnerTests',
  );
}
